### ISSUE TITLE
Brawler 64 Wireless Edition not supported

### ISSUE THREAD

**Issue by MjhX** [raphnet/gc_n64_usb-v3#7]
Unlike the original Brawler 64 (as tested by Utilisateur), the wireless edition of the Brawler 64 controller that was just released does not work with the adapter in 3.6.

**Comment by raphnet** [comment]
Yes, I have heard of this and already ordered a Brawler 64 wireless on the way. Hopefully it will be a simple fix...

**Comment by raphnet** [comment]
This is fixed in release 3.6.1. 

The brawler 64 wireless gamepad does not like when the get caps command is followed
too closely by the get status command. Without a long pause between the two commands,
it just returns all zeros.

The workaround was to add a pause between the two commands, when the poll_interval setting allows it. This means that the Brawler 64 wireless edition will work on 3.6.1 with a poll interval setting >= 2ms, and on dual port adapters, >= 4ms.

**Comment by MjhX** [comment]
Alright, thank you.  I'll be waiting for the 3.6.1 release.

**Comment by raphnet** [comment]
Later there will be a new adapter manager release which will include this new firmware, but if you want to try it now, it can be downloaded from here: https://www.raphnet.net/electronique/gcn64_usb_adapter_gen3/index_en.php#releases

**Comment by MjhX** [comment]
Alright, thanks.
